# Generated by Django 2.0.1 on 2018-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.Category', verbose_name='상위 분류')),
            ],
            options={
                'verbose_name': '분류',
                'verbose_name_plural': '분류',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, '보류'), (2, '완료')], null=True, verbose_name='상태')),
                ('content', models.TextField(verbose_name='내용')),
                ('code_place', models.TextField(verbose_name='코드 위치')),
                ('categories', models.ManyToManyField(to='note.Category', verbose_name='분류')),
            ],
            options={
                'verbose_name': '이슈',
                'verbose_name_plural': '이슈',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_base', models.BooleanField(default=False, verbose_name='기준 카테고리')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.Issue', verbose_name='분류')),
            ],
            options={
                'verbose_name': '메모',
            },
        ),
    ]
